/**
 * This code was generated by Builder.io
 */
import React from "react";
import styles from "./InThisMoment.module.css";

const DetailItem = ({ imageSrc, description }) => {
  return (
    <div className={styles.detailItem}>
      <img
        loading="lazy"
        src={imageSrc}
        alt=""
        className={styles.detailImage}
      />
      <div className={styles.detailDescription}>{description}</div>
    </div>
  );
};

export default DetailItem;
