/**
 * This code was generated by Builder.io
 */
import React from "react";
import styles from "./InThisMoment.module.css";

const FeatureItem = ({ number, description }) => {
  return (
    <div className={styles.featureItem}>
      <div className={styles.featureNumber}>{number}</div>
      <div className={styles.featureDescription}>{description}</div>
    </div>
  );
};

export default FeatureItem;
