/**
 * This code was generated by Builder.io
 */
import React from "react";
import styles from "./InThisMoment.module.css";
import FeatureItem from "./FeatureItem";
import DetailItem from "./DetailItem";

const InThisMoment = () => {
  const features = [
    {
      number: "01",
      description: "Capture Moments Effortlessly with AI-Driven Commands",
    },
    {
      number: "02",
      description:
        "Automatic Transcription and Rich Summaries of Every Experience",
    },
    {
      number: "03",
      description:
        "Relive Your Memories in Real-Time, Right Where They Happened",
    },
  ];

  const details = [
    {
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/1dbd5f28c8d5a9de45c5fa243a49cc69b9759b2ebd2c19a29372ec2258625e5f?placeholderIfAbsent=true&apiKey=db7985d8f6d84e9c9434dc369e493328",
      description:
        "Transform each experience into a lasting memory using intuitive voice commands, image capture, and text input, powered by advanced AI",
    },
    {
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/ba6b52b8351a94d598670f30f051345b2d1915913be54701870cd63b2b0faae8?placeholderIfAbsent=true&apiKey=db7985d8f6d84e9c9434dc369e493328",
      description:
        "Let AI transcribe, record, and enrich your moments with meaningful summaries, so every detail is preserved",
    },
    {
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/b3060fddfe1f9027e4493c80ed16b5abceb146742fce81e2321fa71eea9d7425?placeholderIfAbsent=true&apiKey=db7985d8f6d84e9c9434dc369e493328",
      description:
        "Reconnect with the atmosphere and feelings of each moment, anytime, with AI recreating the experience exactly as it was",
    },
  ];

  return (
    <main className={styles.container}>
      <section className={styles.mainContent}>
        <header>
          <h1 className={styles.logo}>inthismoment.me</h1>
        </header>
        <section className={styles.heroSection}>
          <div className={styles.heroContent}>
            <div className={styles.column}>
              <div className={styles.textContent}>
                <h2 className={styles.title}>
                  Relive Your Memories in Real-Time, Right Where They Happened
                </h2>
                <p className={styles.subtitle}>
                  Relive the moments you cherish through AI powered personal
                  memory tracker
                </p>
                <button className={styles.ctaButton}>Join our waitlist</button>
              </div>
            </div>
            <div className={styles.column}>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/58675012a67c0fbb6ff60d290b0eed9829c3eaa784220663e7cd1dd242663de2?placeholderIfAbsent=true&apiKey=db7985d8f6d84e9c9434dc369e493328"
                alt="AI-powered memory tracker interface"
                className={styles.heroImage}
              />
            </div>
            <div className={styles.column}>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/e766b974f2b72e7c34ee08d83fa98596629091ba9d4a6852d7fb505629799d0d?placeholderIfAbsent=true&apiKey=db7985d8f6d84e9c9434dc369e493328"
                alt="Person using the memory tracker app"
                className={styles.secondaryImage}
              />
            </div>
          </div>
        </section>
        <section className={styles.featuresSection}>
          <div className={styles.featuresList}>
            {features.map((feature, index) => (
              <div key={index} className={styles.column}>
                <FeatureItem
                  number={feature.number}
                  description={feature.description}
                />
              </div>
            ))}
          </div>
        </section>
        <section className={styles.detailsSection}>
          <div className={styles.detailsList}>
            {details.map((detail, index) => (
              <div key={index} className={styles.column}>
                <DetailItem
                  imageSrc={detail.imageSrc}
                  description={detail.description}
                />
              </div>
            ))}
          </div>
        </section>
      </section>
    </main>
  );
};

export default InThisMoment;
