/**
 * This code was generated by Builder.io
 */
import React from "react";
import styles from "./FeatureDetails.module.css";

const featureDetails = [
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/1dbd5f28c8d5a9de45c5fa243a49cc69b9759b2ebd2c19a29372ec2258625e5f?placeholderIfAbsent=true&apiKey=db7985d8f6d84e9c9434dc369e493328",
    description:
      "Transform each experience into a lasting memory using intuitive voice commands, image capture, and text input, powered by advanced AI",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/ba6b52b8351a94d598670f30f051345b2d1915913be54701870cd63b2b0faae8?placeholderIfAbsent=true&apiKey=db7985d8f6d84e9c9434dc369e493328",
    description:
      "Let AI transcribe, record, and enrich your moments with meaningful summaries, so every detail is preserved",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/b3060fddfe1f9027e4493c80ed16b5abceb146742fce81e2321fa71eea9d7425?placeholderIfAbsent=true&apiKey=db7985d8f6d84e9c9434dc369e493328",
    description:
      "Reconnect with the atmosphere and feelings of each moment, anytime, with AI recreating the experience exactly as it was",
  },
];

function FeatureDetails() {
  return (
    <section className={styles.featureDetails}>
      {featureDetails.map((feature, index) => (
        <article key={index} className={styles.featureDetail}>
          <img
            src={feature.image}
            alt={`Feature illustration ${index + 1}`}
            className={styles.featureImage}
          />
          <p className={styles.featureDescription}>{feature.description}</p>
        </article>
      ))}
    </section>
  );
}

export default FeatureDetails;
