/**
 * This code was generated by Builder.io
 */
import React from "react";
import styles from "./Header.module.css";

function Header() {
  return (
    <header className={styles.header}>
      <h1 className={styles.logo}>inthismoment.me</h1>
      <button className={styles.ctaButton}>Join our waitlist</button>
    </header>
  );
}

export default Header;
