/**
 * This code was generated by Builder.io
 */
import React from "react";
import Header from "./Header";
import HeroSection from "./HeroSection";
import FeatureList from "./FeatureList";
import FeatureDetails from "./FeatureDetails";
import styles from "./MemoryTrackerPage.module.css";

function MemoryTrackerPage() {
  return (
    <main className={styles.memoryTracker}>
      <Header />
      <HeroSection />
      <FeatureList />
      <FeatureDetails />
    </main>
  );
}

export default MemoryTrackerPage;
