/**
 * This code was generated by Builder.io
 */
import React from "react";
import styles from "./FeatureCard.module.css";

const FeatureCard = ({ imageSrc, description }) => {
  return (
    <article className={styles.featureCard}>
      <img src={imageSrc} alt="" className={styles.featureImage} />
      <p className={styles.featureDescription}>{description}</p>
    </article>
  );
};

export default FeatureCard;
